version: 2
updates:
  - directory: /
    open-pull-requests-limit: 3
    package-ecosystem: gomod
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    open-pull-requests-limit: 2
    schedule:
      interval: monthly
