version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 6
    schedule:
      interval: monthly
      day: wednesday

  - package-ecosystem: elm
    directory: /web
    schedule:
      interval: monthly
      day: wednesday

  - package-ecosystem: docker
    directories:
    - /
    - /mailer
    open-pull-requests-limit: 2
    schedule:
      interval: monthly
      day: wednesday

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 2
    schedule:
      interval: monthly
      day: wednesday
