version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 3
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directories:
    - /
    - /mailer
    open-pull-requests-limit: 2
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: .github/workflows
    open-pull-requests-limit: 2
    schedule:
      interval: monthly
