services:
  postgres:
    image: postgres:16-alpine
    container_name: onasty-postgres
    environment:
      POSTGRES_USER: onasty
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: onasty
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  prometheus:
    image: prom/prometheus
    container_name: onasty-prometheus
    user: root
    network_mode: host # TODO: remove
    volumes:
      - ./.docker/prometheus:/prometheus
      - ./infra/prometheus:/etc/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:11.1.6
    container_name: onasty-grafana
    network_mode: host # TODO: remove
    user: root
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./.docker/grafana:/var/lib/grafana
      - ./infra/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - 3069:3000
