version: "3"

dotenv:
  - ".env"

includes:
  migrate: ./migrations/Taskfile.yml
  seed: ./cmd/seed/Taskfile.yml

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

tasks:
  run:
    - docker compose up -d --build --remove-orphans core mailer

  lint:
    - golangci-lint run

  docker:up:
    - docker compose up -d --build --remove-orphans

  docker:down:
    aliases: [docker:stop]
    cmds:
      - docker compose stop

  test:
    - task: test:unit
    - task: test:e2e

  test:unit:
    - go test --count=1 -v --short ./...

  test:e2e:
    - go test --count=1 -v ./e2e/
