version: "3"

dotenv:
  - ".env"

includes:
  migrate: ./migrations/Taskfile.yml
  frontend:
    taskfile: ./web/Taskfile.yml
    dir: ./web/

env:
  COMPOSE_BAKE: 1

vars:
  gotest:
    sh: 'command -v gotest >/dev/null && echo gotest || echo "go test"'

tasks:
  run:
    - docker compose up -d --build --remove-orphans core mailer

  lint:
    - golangci-lint run

  docker:up:
    - docker compose up -d --build --remove-orphans

  docker:down:
    aliases: [docker:stop]
    cmd: docker compose stop

  seed:run:
    - docker compose run --rm seed

  test:
    - task: test:unit
    - task: test:e2e
    - task: frontend:test

  test:unit:
    - '{{.gotest}} --count=1 -v --short ./...'

  test:e2e:
    - '{{.gotest}} --count=1 -v ./e2e/'
