version: "3"

env:
  MIGRATIONS_DIR: ./migrations/

tasks:
  new:
    desc: create new migration `new -- <migrationName>`
    cmds:
      - migrate create -ext sql -dir {{.MIGRATIONS_DIR}} {{ .CLI_ARGS }}

  up:
    - migrate -database $POSTGRESQL_DSN  -path {{.MIGRATIONS_DIR}} up

  down:
    - migrate -database $POSTGRESQL_DSN -path {{.MIGRATIONS_DIR}} down 1

  drop:
    - migrate -database $POSTGRESQL_DSN -path {{.MIGRATIONS_DIR}} drop
