{
 "title": "onasty",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "http requests latency",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, method, uri) (rate(http_request_latency_seconds_bucket[5s]))\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (method, uri) (http_successful_requests_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (method, uri) (http_failed_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful / Failed Requests",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, uri) (http_successful_requests_total)",
     "legendFormat": "{{method}} {{uri}}"
    },
    {
     "expr": "sum by (method, uri) (http_failed_requests_total)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{service_name=\"onasty-core\"}\n|= ``\n| json\n| drop container, container_id, service_name\n| label_format cache_miss=\"{{ if eq .err `redis: nil` }}true{{ end }}\""
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"core\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC pause durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 22 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"core\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "mailer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "ratio sent/failed emails",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(mail_sent_total) / clamp_min(sum(mail_sent_total) + sum(mail_failed_total), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 17, "x": 7, "y": 31 },
   "targets": [
    {
     "expr": "{service_name=\"onasty-mailer\"}\n|= ``\n| json\n| drop container, container_id, service_name\n| label_format cache_miss=\"{{ if eq .err `redis: nil` }}true{{ end }}\""
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"mailer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC pause durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 46 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"mailer\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}