global:
  scrape_interval: 5s
  scrape_timeout: 2s
  evaluation_interval: 15s

scrape_configs:
  - job_name: core
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    honor_timestamps: true
    static_configs:
      - targets: [core:8001]
        labels:
          service: "core"

  - job_name: mailer
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    honor_labels: true
    static_configs:
      - targets: [mailer:8001]
        labels:
          service: "mailer"
