global:
  scrape_interval: 5s
  scrape_timeout: 2s
  evaluation_interval: 15s
scrape_configs:
  - job_name: core
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    honor_timestamps: true
    static_configs:
    - targets:
      - core:3001
