name: elm

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4

      - name: Install dependencies
        working-directory: ./web
        run: npm ci

      - name: Linter
        working-directory: ./web
        run: npm run lint

      - name: Test
        working-directory: ./web
        run: npm test
