name: golang

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["*.go", "go.mod", "go.sum"]
  pull_request:
    paths: ["*.go", "go.mod", "go.sum"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.mod

      - name: Build API
        run: go build -o .bin/onasty ./cmd/server/

      - name: Unit tests
        run: go test -v --short ./...

      - name: e2e tests
        run: go test -v ./e2e/

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Golangci Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: ./...
